# This is a basic workflow that is manually triggered
name: Data Deploy

on:
  workflow_dispatch:
    inputs:
      proposalId:
        description: 'Proposal Id'
        required: true
        type: string

jobs:
  greet:
    environment: test
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
