# This is a basic workflow that is manually triggered
name: DAO Deploy

on:
  workflow_dispatch:
    inputs:
      proposalId:
        description: 'Proposal Id'
        required: true
        type: string

run-name: Proposal [ID:${{ inputs.proposalId }}]

jobs:
  deploy:
    environment: test
    runs-on: ubuntu-latest
    steps:
    - name: Dummy
      run: echo "ID:${{ inputs.proposalId }}"
